SELECT * FROM customer LIMIT 20;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue 
FROM customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount ?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- Q3. What are the top 5 products with the highest review rating?
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q4. Compare the average purchase amounts between standard and express shipping.
select shipping_type,
round (AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type


-- Q5. Do subscribed customers spend more? compare avg spend and and total revenue between subscribers and non subscribers
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied ?
SELECT 
    item_purchased,
    ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. SEgment customers into New, Ruturning, and loyal based on their total
-- number of previous purchases, and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count (customer_id)DESC) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased ,total_orders
from item_counts


-- Q9 are customers who are repeat buyers ( more than 5 previous purchases)
-- also likely to subscribe ?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status


--Q10 What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

select current_user;

